service: you-betta-rekognize

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

custom:
  bundle:
    sourcemaps: true
    caching: false
    stats: true
    linting: true
  apiGatewayUrl:
    Fn::Join:
      - ''
      - - 'https://'
        - Ref: ApiGatewayRestApi
        - '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}'
  twitterConsumerAPIKey: ${ssm:/you-betta-rekognize/TWITTER_CONSUMER_API_KEY~true}
  twitterConsumerAPIKeySecret: ${ssm:/you-betta-rekognize/TWITTER_CONSUMER_API_KEY_SECRET~true}
  twitterAccessToken: ${ssm:/you-betta-rekognize/TWITTER_ACCESS_TOKEN~true}
  twitterAccessTokenSecret: ${ssm:/you-betta-rekognize/TWITTER_ACCESS_TOKEN_SECRET~true}

provider:
  name: aws
  profile: personal # Or whatever you named your profile when you configured the Serverless CLI
  region: ${opt:region, 'us-west-2'}
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    API_GATEWAY_URL: ${self:custom.apiGatewayUrl}
    TWITTER_CONSUMER_API_KEY: ${self:custom.twitterConsumerAPIKey}
    TWITTER_CONSUMER_API_KEY_SECRET: ${self:custom.twitterConsumerAPIKeySecret}
    TWITTER_ACCESS_TOKEN: ${self:custom.twitterAccessToken}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.twitterAccessTokenSecret}

functions:
  healthCheck:
    handler: src/functions/healthCheck.handler
    events:
      - http:
          path: healthcheck
          method: post
  getToken:
    handler: src/functions/authorizer.getToken
    events:
      - http:
          path: auth/token
          method: post
