service: you-betta-rekognize

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

custom:
  bundle:
    sourcemaps: true
    caching: false
    stats: true
    linting: true
  apiGatewayUrl:
    Fn::Join:
      - ''
      - - 'https://'
        - Ref: ApiGatewayRestApi
        - '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}'

provider:
  name: aws
  profile: personal # Or whatever you named your profile when you configured the Serverless CLI
  region: ${opt:region, 'us-west-2'}
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    API_GATEWAY_URL: ${self:custom.apiGatewayUrl}

functions:
  healthCheck:
    handler: src/functions/healthCheck.handler
    events:
      - http:
          path: healthcheck
          method: post
